Repository hyperledger/grid, pull requests merged in 2022-04, with the labels that each got.

#1363 Add release notes for v0.3.3
  RELEASE_NOTES.md
Labels: 0-3

#1351 Add `get_batch_status` db operation
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs
  sdk/src/batch_tracking/store/diesel/operations/mod.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main

#1353 Add `DELAYED` batch status type
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main

#1375 Fix over-eager clone
  contracts/purchase_order/src/handler.rs
Labels: Backport-0-3, main

#1376 Backport 0-3: Fix over-eager clone
  contracts/purchase_order/src/handler.rs
Labels: 0-3

#1377 Bump grid-dev version to v10 to differentiate it from 0-3
  ci/grid-dev-buildx
  ci/grid-dev.yaml
  cli/Dockerfile
  contracts/location/Dockerfile
  contracts/pike/Dockerfile
  contracts/product/Dockerfile
  contracts/purchase_order/Dockerfile
  contracts/schema/Dockerfile
  contracts/track_and_trace/Dockerfile
  daemon/Dockerfile
  docker/lint
  docker/tests
  griddle/Dockerfile
Labels: main

#1380 Update batch tracking migrations
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs
  sdk/src/batch_tracking/store/diesel/schema.rs
  sdk/src/batch_tracking/store/mod.rs
  sdk/src/migrations/diesel/postgres/migrations/2022-04-14-215932_add_batch_tracking_tables_2/down.sql
  sdk/src/migrations/diesel/postgres/migrations/2022-04-14-215932_add_batch_tracking_tables_2/up.sql
  sdk/src/migrations/diesel/sqlite/migrations/2022-04-14-215500_add_batch_tracking_tables_2/down.sql
  sdk/src/migrations/diesel/sqlite/migrations/2022-04-14-215500_add_batch_tracking_tables_2/up.sql
Labels: main

#1379 BACKPORT 0-3: Publish multi-arch Docker images
  .github/workflows/0-3-grid-dev.yaml
  .github/workflows/0-3-publish-release.yaml
  ci/docker-bake.hcl
  ci/grid-dev-buildx
  ci/publish-docker
Labels: 0-3

#1345 Add `GET` proxy endpoint for Griddle
  griddle/Cargo.toml
  griddle/src/main.rs
  sdk/Cargo.toml
  sdk/src/lib.rs
  sdk/src/proxy/client/mod.rs
  sdk/src/proxy/client/reqwest.rs
  sdk/src/proxy/error.rs
  sdk/src/proxy/mod.rs
  sdk/src/proxy/request.rs
  sdk/src/proxy/response.rs
  sdk/src/rest_api/actix_web_3/routes/mod.rs
  sdk/src/rest_api/actix_web_3/routes/proxy.rs
  sdk/src/rest_api/actix_web_3/run.rs
  sdk/src/rest_api/resources/agents/v1/payloads.rs
  sdk/src/rest_api/resources/error.rs
Labels: main

#1389 Update protoc to 3.20.0
  ci/grid-dev
  ci/grid-dev-buildx
  ci/grid-dev.yaml
  cli/Dockerfile
  contracts/location/Dockerfile
  contracts/pike/Dockerfile
  contracts/product/Dockerfile
  contracts/purchase_order/Dockerfile
  contracts/schema/Dockerfile
  contracts/track_and_trace/Dockerfile
  daemon/Dockerfile
  docker/lint
  docker/tests
  griddle/Dockerfile
Labels: main

#1388 Undo batch_tracking migrations key changes
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs
  sdk/src/batch_tracking/store/diesel/schema.rs
  sdk/src/migrations/diesel/postgres/migrations/2022-04-19-160501_undo-batch-tracking-key-changes/down.sql
  sdk/src/migrations/diesel/postgres/migrations/2022-04-19-160501_undo-batch-tracking-key-changes/up.sql
  sdk/src/migrations/diesel/sqlite/migrations/2022-04-19-160454_undo-batch-tracking-key-changes/down.sql
  sdk/src/migrations/diesel/sqlite/migrations/2022-04-19-160454_undo-batch-tracking-key-changes/up.sql
Labels: main

#1374 Add `change_batch_to_submitted` operation
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/change_batch_to_submitted.rs
  sdk/src/batch_tracking/store/diesel/operations/mod.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main

#1364 Add `update_batch_status` operation
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/mod.rs
  sdk/src/batch_tracking/store/diesel/operations/update_batch_status.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main

#1381 Add `get_unsubmitted_batches` operation
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch.rs
  sdk/src/batch_tracking/store/diesel/operations/get_unsubmitted_batches.rs
  sdk/src/batch_tracking/store/diesel/operations/mod.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main
