Repository hyperledger/grid, pull requests merged in 2022-05, with the labels that each got.

#1383 Add `list_batches_by_status` operation
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/operations/list_batches_by_status.rs
  sdk/src/batch_tracking/store/diesel/operations/mod.rs
Labels: main

#1393 Add `get_failed_batches` operation
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/operations/get_failed_batches.rs
  sdk/src/batch_tracking/store/diesel/operations/mod.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main

#1419 Use actix-rt library for testing actix async
  sdk/Cargo.toml
  sdk/src/backend/splinter.rs
Labels: backport-triage, main

#1413 Add scope_id and specific batch structs
  sdk/src/batch_tracking/store/mod.rs
  sdk/src/lib.rs
  sdk/src/scope_id/mod.rs
  sdk/src/scope_id/service/id/circuit.rs
  sdk/src/scope_id/service/id/mod.rs
  sdk/src/scope_id/service/id/qualified.rs
  sdk/src/scope_id/service/id/service.rs
  sdk/src/scope_id/service/mod.rs
Labels: backport-triage, main

#1398 Add `clean_stale_records` operation
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/add_batches.rs
  sdk/src/batch_tracking/store/diesel/operations/clean_stale_records.rs
  sdk/src/batch_tracking/store/diesel/operations/mod.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main

#1415 Add `batch_submission` mod and `url_resolver`
  sdk/Cargo.toml
  sdk/src/batch_submission/mod.rs
  sdk/src/batch_submission/submission/mod.rs
  sdk/src/batch_submission/submission/url_resolver/basic_url_resolver.rs
  sdk/src/batch_submission/submission/url_resolver/mod.rs
  sdk/src/lib.rs
Labels: backport-triage, main

#1420 Add submission struct
  sdk/src/batch_submission/mod.rs
Labels: backport-triage, main

#1399 Add support for `data_change_id`s
  sdk/src/batch_tracking/store/diesel/mod.rs
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/diesel/operations/change_batch_to_submitted.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch.rs
  sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs
  sdk/src/batch_tracking/store/diesel/operations/update_batch_status.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: main

#1402 Update batch tracking store doc comments
  sdk/src/batch_tracking/store/mod.rs
Labels: backport-triage, main

#1401 Make `TrackingBatch` `service_id` an `Option`
  sdk/src/batch_tracking/store/diesel/models.rs
  sdk/src/batch_tracking/store/mod.rs
Labels: backport-triage, main

#1400 Clean up `BatchTrackingStore` tests
  sdk/src/batch_tracking/store/diesel/mod.rs
Labels: backport-triage, main

#1432 Update `/batches` endpoint to correctly return errors from Splinter
  sdk/src/backend/splinter.rs
Labels: Backport-0-3, main

#1416 Add REST API batch submission handler trait
  sdk/Cargo.toml
  sdk/src/rest_api/resources/submit/v2/handler/mod.rs
  sdk/src/rest_api/resources/submit/v2/handler/reqwest.rs
  sdk/src/rest_api/resources/submit/v2/mod.rs
  sdk/src/rest_api/resources/submit/v2/payloads/batch.rs
  sdk/src/rest_api/resources/submit/v2/payloads/mod.rs
Labels: main
