Repository hyperledger/grid, pull requests merged in 2022-07, with the labels that each got.

#1454 Fix clippy lint introduced in 1.62.0
  cli/src/actions/agent.rs
  cli/src/actions/organization.rs
  cli/src/actions/purchase_order.rs
  sdk/src/client/reqwest/mod.rs
  sdk/src/lib.rs
Labels: Backport-0-3, main

#1457 Jammy upgrade
  .env
  ci/docker-bake.hcl
  ci/grid-dev-buildx
  ci/grid-dev.dockerfile
  ci/grid-dev.yaml
  ci/publish-grid-crates.dockerfile
  cli/Dockerfile
  contracts/location/Dockerfile
  contracts/pike/Dockerfile
  contracts/product/Dockerfile
  contracts/purchase_order/Dockerfile
  contracts/schema/Dockerfile
  contracts/track_and_trace/Dockerfile
  daemon/Dockerfile
  docker/compose/.env
  docker/lint.dockerfile
  docker/tests.dockerfile
  examples/griddle/.env
  examples/sawtooth/.env
  examples/splinter/.env
  griddle/Dockerfile
  integration/.env
  ui/grid-ui/docker/.env
Labels: backport-triage, main

#1450 Add config object for Griddle
  griddle/Cargo.toml
  griddle/src/config/builder.rs
  griddle/src/config/clap.rs
  griddle/src/config/default.rs
  griddle/src/config/env.rs
  griddle/src/config/error.rs
  griddle/src/config/mod.rs
  griddle/src/config/partial.rs
  griddle/src/main.rs
Labels: Epic: Griddle, main

#1458 Add REST API module to griddle
  griddle/Cargo.toml
  griddle/src/main.rs
  griddle/src/rest_api/actix_web_4/api.rs
  griddle/src/rest_api/actix_web_4/builder.rs
  griddle/src/rest_api/actix_web_4/mod.rs
  griddle/src/rest_api/actix_web_4/runnable.rs
  griddle/src/rest_api/error.rs
  griddle/src/rest_api/mod.rs
Labels: Epic: Griddle, main

#1461 Update Ubuntu / OS X build dependencies
  README.md
Labels: backport-triage, main

#1460 Update ci-test just recipe so unit-tests pass in GHA
  justfile
Labels: backport-triage, main

#1459 Fix typos and add PR test for typos
  .github/typos_config.toml
  .github/workflows/lint-typos.yaml
  ci/publish-grid-crates.dockerfile
  cli/man/grid-location-update.1.md
  cli/src/actions/schema.rs
  contracts/product/src/handler.rs
  contracts/purchase_order/src/handler.rs
  contracts/purchase_order/src/payload.rs
  contracts/schema/src/payload.rs
  contracts/track_and_trace/src/handler.rs
  daemon/src/error.rs
  daemon/src/rest_api/mod.rs
  daemon/src/splinter/app_auth_handler/error.rs
  daemon/src/splinter/app_auth_handler/mod.rs
  docker/typos.dockerfile
  griddle/src/main.rs
  justfile
  sdk/protos/track_and_trace_payload.proto
  sdk/src/batch_processor/pacemaker.rs
  sdk/src/commits/store/diesel/mod.rs
  sdk/src/commits/store/diesel/operations/get_current_service_commits.rs
  sdk/src/pike/permissions/mod.rs
  sdk/src/protocol/pike/payload.rs
  sdk/src/protocol/track_and_trace/payload.rs
  sdk/src/protocol/track_and_trace/state.rs
  sdk/src/rest_api/resources/error.rs
  sdk/src/threading/lifecycle.rs
  ui/protos/track_and_trace_payload.proto
  ui/saplings/product/src/api/transactions.js
Labels: backport-triage, main

#1462 Add just recipe for fixing typos
  justfile
Labels: backport-triage, main

#1464 Upgrade sabre image version in sawtooth example
  examples/sawtooth/docker-compose.yaml
Labels: backport-triage, main
