Repository hyperledger/grid, pull requests merged in 2022-06, with the labels that each got.

#1437 Add release notes for v0.3.4
  RELEASE_NOTES.md
Labels: 0-3

#1438 Test grid-ui docker build in CI
  justfile
Labels: Backport-0-3, main

#1429 Retire chenette and eloaverona
  CODEOWNERS
  MAINTAINERS.md
Labels: main

#1428 Make Chris Eckhardt a Grid maintainer
  CODEOWNERS
  MAINTAINERS.md
Labels: main

#1433 BACKPORT 0-3: Remove slack alerts from pull request workflows
  .github/workflows/0-3-integration-tests.yaml
  .github/workflows/0-3-lint-grid-ui.yaml
  .github/workflows/0-3-lint-grid.yaml
  .github/workflows/0-3-lint-openapi.yaml
  .github/workflows/0-3-test-grid-ui.yaml
  .github/workflows/0-3-unit-test-grid.yaml
Labels: 0-3

#1434 BACKPORT 0-2: Remove slack alerts from pull request workflows
  .github/workflows/0-2-integration-tests.yaml
  .github/workflows/0-2-lint-grid-ui.yaml
  .github/workflows/0-2-lint-grid.yaml
  .github/workflows/0-2-merge.yaml
  .github/workflows/0-2-test-docker-build.yaml
  .github/workflows/0-2-test-grid-ui.yaml
  .github/workflows/0-2-unit-test-grid.yaml
  daemon/src/splinter/app_auth_handler/mod.rs
Labels: 0-2

#1439 BACKPORT 0-3: Test grid-ui docker build in CI
  justfile
  ui/Dockerfile
Labels: 0-3

#1446 Update proxy `From` implementation
  sdk/Cargo.toml
  sdk/src/rest_api/actix_web_4/routes/proxy.rs
Labels: main

#1447 Update maintainer name
  CODEOWNERS
  MAINTAINERS.md
Labels: backport-triage, main

#1448 Add copyright to Griddle's Cargo.toml file
  griddle/Cargo.toml
Labels: main

#1449 Add Shutdown trait
  sdk/Cargo.toml
  sdk/src/lib.rs
  sdk/src/threading/lifecycle.rs
  sdk/src/threading/mod.rs
Labels: main

#1452 Clean up unused imports in scope_id tests
  sdk/src/scope_id/service/id/circuit.rs
  sdk/src/scope_id/service/id/service.rs
Labels: backport-triage, main
